### ISSUE TITLE
NPE happened when parse webdav.xsd

### ISSUE THREAD

**Issue by synix** [yeshodhan/android-jaxb#17]
When parse  [webdav.xsd](https://github.com/lookfirst/sardine/blob/master/webdav.xsd)  NPE happened:

⇒  java -jar  ./android-jaxb-1.0.1.jar webdav.xsd -d src/main/java -p com.github.sardine.model
Code Generator Initialized. Destination Directory: src/main/java
[Element /activelock    Min Occurs: null, Max Occurs: null ] of type [null][Start of sequence Min Occurs: 1, Max Occurs: 1 ]
	[Element /activelock/lockscope    Min Occurs: 1, Max Occurs: 1 ] of type [null]Exception in thread "main" java.lang.NullPointerException
	at com.mickoo.xml.xsd2simplexml.NameUtil.toWordList(NameUtil.java:208)
	at com.mickoo.xml.xsd2simplexml.NameConverter$Standard.toWordList(NameConverter.java:106)
	at com.mickoo.xml.xsd2simplexml.NameConverter$Standard.toClassName(NameConverter.java:108)
	at com.mickoo.xml.xsd2simplexml.CodeGenerator.createElement(CodeGenerator.java:43)
	at com.mickoo.xml.xsd2simplexml.SchemaParser.processElement(SchemaParser.java:347)
	at com.mickoo.xml.xsd2simplexml.SchemaParser.processParticle(SchemaParser.java:208)
	at com.mickoo.xml.xsd2simplexml.SchemaParser.processGroup(SchemaParser.java:219)
	at com.mickoo.xml.xsd2simplexml.SchemaParser.processParticle(SchemaParser.java:204)
	at com.mickoo.xml.xsd2simplexml.SchemaParser.processComplexType(SchemaParser.java:232)
	at com.mickoo.xml.xsd2simplexml.SchemaParser.processElement(SchemaParser.java:368)
	at com.mickoo.xml.xsd2simplexml.SchemaParser.parse(SchemaParser.java:67)
	at com.mickoo.xml.xsd2simplexml.Main.main(Main.java:80)

**Comment by milkovn** [comment]
I have a similar issue. Did you manage to solve it?

**Comment by de-graeuler** [comment]
I had a similar issue using the downloadable jar. When I tried digging into it running it from the IDE the problem vanished.
