### ISSUE TITLE
NullPointerException thrown while parsing IAB VAST 2.0.1 XSD

### ISSUE THREAD

**Issue by Unlimity** [yeshodhan/android-jaxb#5]
Hello there!
I tried to use this library to convert IAB's VAST 2.0.1 XSD for my current project and issued this exception:

``` java
Exception in thread "main" java.lang.NullPointerException
    at com.mickoo.xml.xsd2simplexml.NameUtil.toWordList(NameUtil.java:208)
    at com.mickoo.xml.xsd2simplexml.NameConverter$Standard.toWordList(NameConverter.java:106)
    at com.mickoo.xml.xsd2simplexml.NameConverter$Standard.toClassName(NameConverter.java:108)
    at com.mickoo.xml.xsd2simplexml.CodeGenerator.createElement(CodeGenerator.java:43)
    at com.mickoo.xml.xsd2simplexml.SchemaParser.processElement(SchemaParser.java:323)
    at com.mickoo.xml.xsd2simplexml.SchemaParser.processParticle(SchemaParser.java:208)
    at com.mickoo.xml.xsd2simplexml.SchemaParser.processGroup(SchemaParser.java:219)
    at com.mickoo.xml.xsd2simplexml.SchemaParser.processParticle(SchemaParser.java:204)
    at com.mickoo.xml.xsd2simplexml.SchemaParser.processComplexType(SchemaParser.java:232)
    at com.mickoo.xml.xsd2simplexml.SchemaParser.processElement(SchemaParser.java:344)
    at com.mickoo.xml.xsd2simplexml.SchemaParser.parse(SchemaParser.java:67)
    at com.mickoo.xml.xsd2simplexml.Main.main(Main.java:80)
```

You can download this xsd at [IAB](http://www.iab.com/wp-content/uploads/2015/11/VAST_2_0_1_Schema.zip)
I hope you can solve the issue or point me out where to search for answer.
Thanks in advance!

**Comment by yeshodhan** [comment]
I've checked few interim fixes for making the VAST schema work. See [vast.zip](https://github.com/yeshodhan/android-jaxb/files/85301/vast.zip)
There are a lot of anonymous complex types, that were causing issues.

Could you please pull or use the attached file, and let me know if it works? If yes, I'll make a new release a new version with the fixes.
[android-jaxb-1.0.1-jar-with-dependencies.jar.zip](https://github.com/yeshodhan/android-jaxb/files/85304/android-jaxb-1.0.1-jar-with-dependencies.jar.zip)

**Comment by jrkoiter** [comment]
I ran into the same NullPointerException, but with a different XSD. Using the version linked in the previous comment fixed the issue. That is: generation finishes without error. I still need to verify the generated classes though.

**Comment by yshahak** [comment]
I had the same problem. the `android-jaxb-1.0.1-jar-with-dependencies.jar.zip` managed to generate the files. But I needed to do a lot of changes as it didn't convert properly some of the elements.

**Comment by ghost** [comment]
its been a while since i post my problem. and no response from the
developer.
my workaround, i just use other alternatives
